sudo: required

services:
  - docker
  
language: node_js

node_js:
  - "12"

cache:
  directories:
    - "node_modules"

before_install:
  - docker pull rqlite/rqlite:4.5.0
  - docker run -d -p 4001:4001 -p4002:4002 --name=rqlite-js rqlite/rqlite:4.5.0

script:
  - npm run build-all
  - npm run test-build -- --reporter tap
  - npm run test-build-integrations -- --reporter tap
  - docker stop rqlite-js
  - docker rm rqlite-js