sudo: required

services:
  - docker
  
language: node_js

node_js:
  - "6"

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@5
  - docker pull rqlite/rqlite
  - docker run -d -p 4001:4001 -p4002:4002 rqlite/rqlite

script:
  - npm run build
  - npm run test-build
  - npm run test-build-integrations